conda install yaml
conda install shapely
conda install pyyaml
pip install scipy
pip install easydict
pip install tensorboardX
pip install mpi4py==2.0.0
pip install gaft
conda install pytorch=0.3.1
pip install torchvision
pip install opencv-python==3.1.0.5
pip install numpy==1.12.1
pip install hyperopt
pip install ray==0.6.3
pip install requests